[package]
name = "quadtree"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = { version = "0.3", features = [ "html_reports" ] }

[[bench]]
name = "quadtree_benchmark"
harness = false

